version: "3.6"

services:
  server:
    image: node:11-alpine
    volumes:
      - ./server:/server_code
    working_dir: /server_code
    ports:
      - 3000:3000
    entrypoint: ash
    command: -c "npm i && npm run server:dev"
    depends_on:
      - db
  client:
    image: node:11-alpine
    entrypoint: ash
    ports:
      - 3001:3001
    volumes:
      - ./client:/client_code
    working_dir: /client_code
    depends_on:
      - server
  db:
    image: postgres:11.5-alpine
    volumes:
      - ./server/db:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: "job_swap"
      POSTGRES_USER: "job_swap"
      POSTGRES_DB: "job_swap"
      PGDATA: ./server/db
